USE master
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '$(SONAR_DB)')
BEGIN
  CREATE DATABASE $(SONAR_DB) COLLATE Latin1_General_100_CS_AS
  ALTER DATABASE $(SONAR_DB) SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE
  ALTER DATABASE $(SONAR_DB) SET ENABLE_BROKER
END;
GO

IF NOT EXISTS(SELECT * FROM sys.database_principals WHERE name = '$(SONAR_USER)')
BEGIN
    CREATE LOGIN $(SONAR_USER) WITH PASSWORD = '$(SONAR_PASSWORD)', DEFAULT_DATABASE = $(SONAR_DB)
    USE $(SONAR_DB)
    CREATE USER $(SONAR_USER) FOR LOGIN $(SONAR_USER)
    EXEC sp_addrolemember 'db_owner', '$(SONAR_USER)'
END;
GO